### PR TITLE
Fixed race conditions in Child and Pool classes

### PR DESCRIPTION
**Pull request by damoclark**
Hi Henrique,

I am using your Process library in a small project I am working on, and I found a race condition that sometimes causes a child process to exit with error status, when in fact it didn't. Thought I'd contribute back my fix.  Hope it proves useful.

I'm very new to github and to pull requests, so hopefully I have done this correctly.  Let me know if something isn't right.

Details follow.

Regards,
Damien.

The Child class' wait method checks the isRunning method to determine whether the child has terminated or not.  However, a race condition exists where the process has terminated before the wait method is called.  In this case, isRunning returns false, and then the wait method will return false, rather than calling waitpid to reap the process and get the status.  Instead of checking isRunning, the method now checks to see if the status has been set in the instance already.  If not, then the wait method hasn't been previously called for this child and so it calls the waitpid function.

In Pool class, it checks if the child process is running by again calling its isRunning method.  If the child process terminates before the wait method of Pool is called, then again the Child object's wait method is never called.  The test for whether isRunning is false for the Child object is omitted, so that it must call the wait method of the Child object.  If the child has already had its wait method called, then it will just return false as intended.

### CODE REVIEW

**Comment by henriquemoody** [comment]
Nice catch! Thanks for sharing

**Comment by henriquemoody** [comment]
The only problem I see is because the build is broken, after running composer, try a `make quality-assurance` then you can see the problems and fix them. If you need any help, just tell me. :smile:

**Comment by damoclark** [comment]
I'll take a look at the results of the failed tests and see what needs to be fixed and push the changes into the branch. If I get stuck, I'll contact you. :)

Damien.

**Comment by damoclark** [comment]
Hi Henrique,

Please take a look at the changes to the unit tests.  Just check that the updated tests still validate what they are supposed to.

**Comment by henriquemoody** [comment]
Thank you very much!

**Pull request merged**
